#!/bin/bash
# Walking a grid

trap "/usr/bin/killall -q -u $USER Heatmap 2>/dev/null" 0 1 2 3 9 15
trap "/bin/rm -f $STDERR" 0 1 2 3 9 15

/c/cs474/bin/run -stderr=/dev/null ./Heatmap 0.03125 0.03125 .xX* 1 < /c/cs223/hw3/Tests/grid_walk_6_4.in
