#!/bin/bash
# Valgrind

trap "/usr/bin/killall -q -u $USER Heatmap 2>/dev/null" 0 1 2 3 9 15
trap "/bin/rm -f $STDERR" 0 1 2 3 9 15

/c/cs474/bin/run -stdout=/dev/null -stderr=/dev/null /usr/bin/valgrind --tool=memcheck --leak-check=yes -q  --log-file=valgrind.out ./Heatmap 0.003 0.002 .:xX# 10 < /c/cs223/hw3/Tests/east_rock.in
cat valgrind.out
